### ISSUE TITLE
Repository interface in the application layer

### ISSUE THREAD

**Issue by Miguel328** [ivanpaulovich/hexagonal-architecture-acerola#10]
Hello,
I am wondering why do you added repository interfaces in the application layer? Many examples show the interfaces in the domain layer.

**Comment by matiienkodimitri** [comment]
Hi Miguel,  I have n t , it is not my code.

but by the way

that is not a bad pratice cuz according to the Vaugh Vernon Red Book, application services can access Repositories so, its not a bad thing to put their interfaces near them

**Comment by ivanpaulovich** [comment]
Hi @Miguel328,

The classic **Hexagonal Architecture Style** define as **Ports** the interfaces exposed by the application and as **Adapters** the implementation required to consume external sources or their fake implementations.

It is more clear when you see this representation:

![Hexagonal Architecture](https://paulovich.net/img/ports-and-adapters-video-thumb.jpg "Hexagonal Architecture")

Of course, you can add the interfaces of Repositories and Services to the Domain, it makes things easier. 

The folders is this case are  just organizational.

Best!
