### ISSUE TITLE
Question about structure of your project

### ISSUE THREAD

**Issue by lowdev** [ivanpaulovich/hexagonal-architecture-acerola#11]
Hi,

I'm new in architecture hexagonal approach.
And I have some question/remarks about your project.
- What is "application" folder ?
- I expected to have port in "domain"
- there is no "domain service" in "domain"
In architecture hexagonal I think service from "application" should be in domain.

I like useCase class approach. This is an approach from DDD ?

Thanks for your project.

**Comment by kaiqueprazeres** [comment]
Hello @lowdev, if I may respond..

This project is very simple. It's a game. It doesn't seem to me to justify using an architecture as robust as the hexagonal architecture or domain-driven software design approaches like DDD. I believe that from the points you raised, the game developer only applied the ubiquitous DDD language. I don't know whether intentionally or unconsciously.

**Comment by lowdev** [comment]
@kaiqueprazeres, thank you for your response.
I thought this project was a hexagonal architecture example.
I guess you are right all projects are not meant to be in hexagonal.
Thank you for your comment.

**Comment by kaiqueprazeres** [comment]
@lowdev , 

Sorry, but my comment doesn't make sense. I had another browser tab open on the "issues" page to respond to another comment like this on another simple project, which I refer to in the answer. I ended up getting confused and answered in the wrong place. Sorry for the error. Ignore what I said.
