### ISSUE TITLE
MediatR

### ISSUE THREAD

**Issue by marcrib** [ivanpaulovich/hexagonal-architecture-acerola#9]
Olá, parabéns pelo projeto.

Por que da remoção do MediatR?

**Comment by ivanpaulovich** [comment]
Olá!

Eu adotei um princípio no _Acerola_ e no _Manga_ que é reduzir ao máximo as dependências externas, e aquilo que eu fizesse questão  de utilizar deveria ser usado como **library** com Inversão de Controle.

No caso do MediatR, a maneira sugerida requer que as classes da camada Application implementem as interfaces do **MediatR framework**, o que gera uma dependência indesejada que se espalha no coração da aplicação.

Além do mais, eu não vi situações onde eu precisasse executar *comandos encadeados* (pipelines do MediatR) o que seria um grande benefício.

:)
